"""Initial migration1

Revision ID: ef8a8a6122c4
Revises: 
Create Date: 2025-09-24 13:29:44.072248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef8a8a6122c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_notifications_id'), 'admin_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_admin_notifications_message'), 'admin_notifications', ['message'], unique=False)
    op.create_index(op.f('ix_admin_notifications_type'), 'admin_notifications', ['type'], unique=False)
    op.create_table('admin_send_sms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_of_recipients', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_send_sms_id'), 'admin_send_sms', ['id'], unique=False)
    op.create_index(op.f('ix_admin_send_sms_message'), 'admin_send_sms', ['message'], unique=False)
    op.create_index(op.f('ix_admin_send_sms_number_of_recipients'), 'admin_send_sms', ['number_of_recipients'], unique=False)
    op.create_index(op.f('ix_admin_send_sms_status'), 'admin_send_sms', ['status'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('share_code', sa.String(), nullable=True),
    sa.Column('share_url', sa.String(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('sold_out', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('updated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_category'), 'bookings', ['category'], unique=False)
    op.create_index(op.f('ix_bookings_deadline'), 'bookings', ['deadline'], unique=False)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_share_code'), 'bookings', ['share_code'], unique=True)
    op.create_index(op.f('ix_bookings_share_url'), 'bookings', ['share_url'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('is_superuser', sa.Integer(), nullable=True),
    sa.Column('is_staff', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_team', sa.String(), nullable=True),
    sa.Column('away_team', sa.String(), nullable=True),
    sa.Column('tournament', sa.String(), nullable=True),
    sa.Column('sport', sa.String(), nullable=True),
    sa.Column('odds', sa.Float(), nullable=True),
    sa.Column('prediction', sa.String(), nullable=True),
    sa.Column('match_status', sa.String(), nullable=True),
    sa.Column('match_day', sa.DateTime(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_away_team'), 'games', ['away_team'], unique=False)
    op.create_index(op.f('ix_games_home_team'), 'games', ['home_team'], unique=False)
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_index(op.f('ix_games_match_day'), 'games', ['match_day'], unique=False)
    op.create_index(op.f('ix_games_match_status'), 'games', ['match_status'], unique=False)
    op.create_index(op.f('ix_games_odds'), 'games', ['odds'], unique=False)
    op.create_index(op.f('ix_games_prediction'), 'games', ['prediction'], unique=False)
    op.create_index(op.f('ix_games_sport'), 'games', ['sport'], unique=False)
    op.create_index(op.f('ix_games_tournament'), 'games', ['tournament'], unique=False)
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchases_id'), 'purchases', ['id'], unique=False)
    op.create_index(op.f('ix_purchases_reference'), 'purchases', ['reference'], unique=True)
    op.create_index(op.f('ix_purchases_status'), 'purchases', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchases_status'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_reference'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_id'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_games_tournament'), table_name='games')
    op.drop_index(op.f('ix_games_sport'), table_name='games')
    op.drop_index(op.f('ix_games_prediction'), table_name='games')
    op.drop_index(op.f('ix_games_odds'), table_name='games')
    op.drop_index(op.f('ix_games_match_status'), table_name='games')
    op.drop_index(op.f('ix_games_match_day'), table_name='games')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_index(op.f('ix_games_home_team'), table_name='games')
    op.drop_index(op.f('ix_games_away_team'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_bookings_share_url'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_share_code'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_deadline'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_category'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_admin_send_sms_status'), table_name='admin_send_sms')
    op.drop_index(op.f('ix_admin_send_sms_number_of_recipients'), table_name='admin_send_sms')
    op.drop_index(op.f('ix_admin_send_sms_message'), table_name='admin_send_sms')
    op.drop_index(op.f('ix_admin_send_sms_id'), table_name='admin_send_sms')
    op.drop_table('admin_send_sms')
    op.drop_index(op.f('ix_admin_notifications_type'), table_name='admin_notifications')
    op.drop_index(op.f('ix_admin_notifications_message'), table_name='admin_notifications')
    op.drop_index(op.f('ix_admin_notifications_id'), table_name='admin_notifications')
    op.drop_table('admin_notifications')
    # ### end Alembic commands ###
